server:
  port: 8080
spring:
  application:
    name: QuickShort-api
  data:
    #Datasource configuration
    mongodb:
      uri: mymongourl
    #Redis configuration
    redis:
      database: 0
      host: myredishost
      port: 00000
      password: myredispassword
      timeout: 60000
  #Kafka configuration
  kafka:
    bootstrap-servers: pkc-12576z.us-west2.gcp.confluent.cloud:9092
    properties:
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_USERNAME} password=${KAFKA_PASSWORD};
    security:
      protocol: SASL_SSL
    topic:
      name: quickshort
    consumer:
      group-id: quickshort
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        request.timeout.ms: 70000
        max.poll.interval.ms: 300000
        max.poll.records: 500
        spring:
          json:
            trusted:
              packages: '*'
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      fetch-max-wait: 60000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      client-id: redirecturl
    listener:
      poll-timeout: 60000
#Swagger configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  open-api:
    info:
     title: QuickShort API Documentation
     description: This is the API documentation for the QuickShort API
     version: 1.0.0
     #termsOfService: https://quickshort.com/terms
     license:
       name: MTI License
       url: https://github.com/Great-Side-Projects/quickshortapi/blob/main/LICENSE
     contact:
       name: Angel Morales
       email: angelmoralesb@gmail.com